package everest.hotel.repository;

public class CommentRepository {

}

// COMMENT_CODE VARCHAR2(10) NOT NULL CONSTRAINT COMMENT_CODE_PK PRIMARY KEY,
// --댓글코드(PK)
// RECOMMENT_CODE VARCHAR2(10) NOT NULL CONSTRAINT RECOMMENT_COMMENT_CODE_FK
// REFERENCES COMMENT_TABLE(COMMENT_CODE), --대댓글코드(FK)
// COMMENT_CONTENT VARCHAR2(500) NOT NULL, --댓글내용
// COMMENT_RDATE DATE NOT NULL, --댓글작성날짜
// MEMBER_ID VARCHAR2(30) NOT NULL CONSTRAINT COMMENT_MEMBER_ID_FK REFERENCES
// MEMBER_TABLE(MEMBER_ID), --회원(FK)
// BOARD_CODE VARCHAR2(10) NOT NULL CONSTRAINT COMMENT_BOARD_CODE_FK REFERENCES
// BOARD_TABLE(BOARD_CODE) --게시판(FK)
// );
// CREATE SEQUENCE COMMENT_TABLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

// INSERT INTO COMMENT_TABLE VALUES(COMMENT_TABLE_SEQ.NEXTVAL,
// COMMENT_TABLE_SEQ.CURRVAL, '댓글이다', SYSDATE, 'P123@NAVER.COM', 1);
// INSERT INTO COMMENT_TABLE VALUES(COMMENT_TABLE_SEQ.NEXTVAL,
// COMMENT_TABLE_SEQ.CURRVAL, '나도댓글', SYSDATE, 'T123@NAVER.COM', 2);
// INSERT INTO COMMENT_TABLE VALUES(COMMENT_TABLE_SEQ.NEXTVAL, 1, '대댓글!',
// SYSDATE, 'Y123@NAVER.COM', 1);
// INSERT INTO COMMENT_TABLE VALUES(COMMENT_TABLE_SEQ.NEXTVAL, 2, '이것도대댓글!',
// SYSDATE, 'Y123@NAVER.COM', 2);