package everest.hotel.repository;

public class PayRepository {

}

// PAY_CODE VARCHAR2(10) NOT NULL CONSTRAINT PAY_CODE PRIMARY KEY, --결제CODE(PK)
// RESERVE_CODE VARCHAR(10) NOT NULL CONSTRAINT PAY_RESERVE_CODE_FK REFERENCES
// RESERVE_TABLE(RESERVE_CODE), --예약CODE(FK)
// PAY_MONEY NUMBER(20) NOT NULL, --결제금액
// PAY_WHAT VARCHAR(10) NOT NULL, --결제수단
// PAY_BANK VARCHAR(10) NOT NULL, --결제은행
// PAY_DAY DATE NOT NULL --결제일시
// );

// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE1',
// 200000, '카드', '농협', '2023-07-11');
// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE2',
// 200000, '카드', '농협', '2023-07-12');
// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE3',
// 200000, '카드', '농협', '2023-06-26');
// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE4',
// 200000, '카드', '농협', '2023-06-26');
// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE5',
// 200000, '카드', '농협', '2023-06-26');
// INSERT INTO PAY_TABLE VALUES('PAY'||PAY_TABLE_SEQ.NEXTVAL, 'RESERVE6',
// 200000, '카드', '농협', '2023-06-26');
